language: php

php:
  - 5.3

mysql:
  database: formframe_test_db
  username: root
  encoding: utf8

install:
  # install drush 5.x (because 6.x's test-run doesn't exit with proper status code).
  - pear channel-discover pear.drush.org
  - pear install drush/drush-5.10.0.0
  - phpenv rehash

  # install additional requirements
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # install javascript unit test requisites
  - npm install
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  - cd ../..

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database formframe_test_db'
  - php -d sendmail_path=`which true` `pear config-get php_dir`/drush/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/formframe_test_db --enable=simpletest formframe

  # reference and enable form frame in the build site
  - ln -s $(readlink -e $(cd -)) formframe/drupal/sites/all/modules/formframe
  - cd formframe/drupal
  - drush --yes pm-enable formframe
  - drush cc all

  # start a web server on port 8080
  - drush runserver 127.0.0.1:8080 &
  - sleep 4
  - drush vset --yes simpletest_verbose FALSE

script:
  # Run JavaScript unit tests.
  - cd $TRAVIS_BUILD_DIR && grunt test

  # Run Drupal unit and behavior tests.
  - cd ../.. && drush test-run 'Form Frame' --uri=http://127.0.0.1:8080
